apiVersion: v1
kind: Pod
metadata:
  name: mssql-pod
  labels:
    app: servicio-bmatic
    name: mssql-pod
spec:
  containers:
  - name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
    - containerPort: 1433
    env:
    - name: ACCEPT_EULA
      value: "Y"
    - name: SA_PASSWORD
      value: "Server1"