apiVersion: v1
kind: Pod
metadata:
  name: servicio-cliente-pod
  labels:
    app: servicio-cliente
spec:
  containers:
  - name: servicio-cliente
    image: jlbedrillanadk/servicio-cliente:1.0
    ports:
    - containerPort: 8081