apiVersion: v1
kind: Pod
metadata:
  name: servicio-bmatic-pod
  labels:
    app: servicio-bmatic
    name: servicio-bmatic-pod
spec:
  containers:
  - name: servicio-bmatic
    image: devduv/api-image:latest
    ports:
    - containerPort: 8091