kind: Service
apiVersion: v1
metadata:
  name: servicio-bmatic-service
spec:
  type: LoadBalancer
  selector:
    app: servicio-bmatic
    name: servicio-bmatic-pod
  ports:
  - protocol: TCP
    port: 8091
    targetPort: 8091
